#!/bin/bash

set -e

. /usr/local/etc/innobackupex_config

[ -d "$BACKUP_DATADIR" ] && rm -rf "$BACKUP_DATADIR"

touch /var/log/backup.log
echo "Backup d: $(date)" >> /var/log/backup.log

innobackupex --use-memory=4G --no-timestamp  --user root "$BACKUP_DATADIR" >> /var/log/backup.log 2>&1

tar cj "$BACKUP_DATADIR"

echo "END - Backup d: $(date)" >> /var/log/backup.log
